name: Build and Publish Docker
on: [push, pull_request]
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Build
      run: docker build --tag ${{ secrets.DOCKER_USERNAME }}/headless:latest .

    - name: Docker login
      run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Publish to Docker Repository
      run: docker push ${{ secrets.DOCKER_USERNAME }}/headless:latest
